@startuml
'https://plantuml.com/class-diagram
class TiGia{
    + void attach(TiGiaListener listener)
    + void detach(TiGiaListener listener)
    + void notify(float delta)
}
abstract class NhaDauTu
class NhaDauTuA
class NhaDauTuB
interface TiGiaLisener{
    void listen(float delta)
}
TiGia o--> TiGiaLisener: Listerners
TiGiaLisener <|.. NhaDauTu
NhaDauTu --> TiGia: t
NhaDauTu <|-- NhaDauTuA
NhaDauTu <|-- NhaDauTuB

@enduml