@startuml
'https://plantuml.com/class-diagram
class LoggerDuy{
- {static} LoggerDuy instance
- Logger()
+ {static} LoggerDuy getInstance()
+ void writeLog(logItem log)
+ void viewLog()
}
class ProgramDuy{
- String id;
+ writeLog(String noiDung, String thoiGian)
}
class LogItem{
- String noiDung, tg, proId
}
LoggerDuy o--> LogItem: logItem
ProgramDuy ..> LoggerDuy
@enduml